version: '2'
services:
  front:
    build: ./front
    ports:
      - "80:3000"
    links:
      - users
      - authors
  users:
    build: ./users
    environment:
      - DATABASE_URL=root:root@tcp(db:3306)/users?parseTime=true&clientFoundRows=true
    links:
      - db
  authors:
    build: ./authors
  db:
    image: mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
